version: '2'
services:
    jhipstercrmapplication-app:
        image: jhipstercrmapplication
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstercrmapplication-mysql:3306/jhipstercrmapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipstercrmapplication-elasticsearch:9300
        ports:
            - 8080:8080
    jhipstercrmapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipstercrmapplication-mysql
    jhipstercrmapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstercrmapplication-elasticsearch
